### ISSUE TITLE
sa-token的配置项在哪里，我看MySaTokenConfig.java中的代码都被注释了

### ISSUE THREAD

**Issue by yuanfengcaichen** [click33/sa-fast#1]

**Comment by click33** [comment]
MySaTokenConfig.java只是为了提供个示例，sa-fast中采用的是yml配置方式，具体可参考一下sa-token的两种配置方式
http://sa-token.dev33.cn/doc/#/use/config

**Comment by yuanfengcaichen** [comment]
两种配置方法一种代码一种yml这个我知道，但是sf-server项目中的application.yml和application-dev.yml这两个文件我都没有找到sa-token相关的配置项

**Comment by click33** [comment]
没配置就是走的默认配置，sa-token可以0配置启动，你如果有定制化需求，可以直接从yml里写配置就行了

**Comment by yuanfengcaichen** [comment]
哦哦明白了，谢谢楼主
